= Camunda HELM Charts
Doc Writer <paul.lungu@camunda.com>
v1.0, 2020-08-13
:toc:

== Goals
- Simple and understandable HELM Optimize example
- Help understand common configuration and architectural concepts
- Good documentation and example to assist in getting Optimize running quickly in Kubernetes
- *NOT* intended as a production ready configuration


== What is configured in this chart
- [x] Optimize
- [x] Optimize EE Repo Pull
- [x] Optimize License
- [x] Load Balancer with sticky sessions
- [x] Elastic Search


== How does it work

IMPORTANT: The configs in this chart are preconfigured defaults and serve as a quick reference for understanding. *You may need to change and adjust things to suit your use-case, infra, architecture, etc ...*

- The HELM chart is an install descriptor to install Optimize on Kubernetes. HELM can do many things to help install and manage infra on Kubernetes.
- The primary configuration point is the values.yaml. It should allow you to get a basic Optimize configuration installed and running with little to no customizations.
- You still need to know how to debug on Kubernetes. See the https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/[Kubernetes Docs] for help.
- While this chart defines how Optimize is installed other components need to be installed in your Kubernetes cluster to make Optimize work. See <<steps-to-run, Setting up Infra>> to install the other components.
- You can find more on HELM here https://helm.sh/docs/intro/quickstart/[Helm Quickstart]

== [[steps-to-run]]Steps to run this HELM chart

==== *STOP* before you run it
====
*Step 0. <<install-helm, Install HELM and Kubernetes>>* if not already installed

*Step 1. <<install-ingress-controller, Install Ingress Contorller>> to configure the loadbalaner ingress controller*

*Step 2. <<configure-external-elastic-search, Install and Configure Elastic Search>> in the Kubernetes cluster*

*Step 3. <<run-camunda, Run Camunda>> you will need a Camunda instance Optimize can pull data from*

*Step 4. <<optimize-version, Configure Optimize Version>>*

*Step 5. <<optimize-connections, Configure Optimize Connections>> to Camunda and Elastic Search*

*Step 6. <<optimize-license, Install Optimize License>>*

*Step 6. <<optimize-run, Run Optimize>>*
====


== [[setup-infra]] Setup Infra and Architecture for Optimize

==== [[install-helm]] *Step 0:* Install HELM and Kubernetes
====
- You can find more on HELM here https://helm.sh/docs/intro/quickstart/[Helm Quickstart]
- https://kubernetes.io/docs/setup/[Kubernetes Getting Started]
- Try https://www.docker.com/products/docker-desktop[Docker Desktop] imo it's the quickest way to get started with Kubernetes

- Tested with HELM
** `version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

- Tested with Kubernetes
** `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}`

** `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`

====

==== [[install-ingress-controller]] *Step 1:* Install Ingress Controller with Sticky Sessions
====
IMPORTANT: Kubernetes does not come with an implementation of a LoadBalancer or a Reverse Proxy for Ingress. The Ingerss resource allows you to configure a Controller for your needs. It's important to understand what you need from an inrgess resource then you can choose the appropriate Controller to install. There are a variety of vendors.

*Tested with* https://kubernetes.github.io/ingress-nginx/deploy/#docker-for-mac

*Install the NGINX Ingress Controller*
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/cloud/deploy.yaml
----
====

---

===== Configure the Ingress resource for Nginx with sticky sessions
====
Update the values.yaml and configure the Ingress Resource to tell the LoadBalancer (the NGINX deployment that was installed above) to stick to one Optimize instance once the user is logged into the webapps.

*Defaults Below*
[source,yaml]
----
  ingress:
    enabled: true
    annotations: {
        nginx.ingress.kubernetes.io/ingress.class: nginx,
        nginx.ingress.kubernetes.io/affinity: "cookie",
        nginx.ingress.kubernetes.io/affinity-mode: "persistent",
        nginx.ingress.kubernetes.io/session-cookie-expires: "172800",
        nginx.ingress.kubernetes.io/session-cookie-max-age: "172800",
      }
      # see more config options https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: optimize.127.0.0.1.nip.io
        paths: ["/"]
    tls: []
    #  - secretName: camunda-optimize-tls
    #    hosts:
    #      - camunda-optimize.local   - camunda-optimize.local

----
====

---

===== Increase the replica count of the Nodes
====

Update the values.yaml and increase the replica count so the load balancer will send requests to both nodes for a user that is not already logged in to web apps.

*Defaults Below*
[source,yaml]
----
general:
  debug: true
  replicaCount: 2
  nameOverride: ""
  fullnameOverride: ""
----
====

---

===== Troubleshoot Kubernetes Resources
====
*Troubleshoot Ingress, Pods and Services*

* Check the Service and Ingress endpoints
** `kubectl describe ingress optimize-demo-camunda-optimize`
** `kubectl describe service optimize-demo-camunda-optimize`

* Check the pods
** `kubectl describe pods optimize-demo-camunda-optimize`

* Check that the Service Selectors get the pods
** `kubectl get pods --show-labels | egrep 'app.kubernetes.io/instance=optimize-demo,app.kubernetes.io/name=camunda-optimize'`
====

---

[[configure-external-elastic-search]]
=== *Step 2:* Configure an External Elastic Search Instance

*Download the Elastic HELM charts*

Download with GIT: https://github.com/elastic/helm-charts[Elastic HELM Charts]

*Update the values.yaml*
Update the values.yaml in for the correct version of Elastic. *Tested with 7.11.2* in the https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/docker-for-mac[Docker for Mac Examples].

*Use Values Below*
[source,yaml]
----
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

imageTag: "7.11.2"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 1G

----

Run the install
[source, sh]
----
make install
----

Test the install
[source, sh]
----
  kubectl port-forward svc/elasticsearch-master 9200

  curl localhost:9200/_cat/indices
----

=== [[run-camunda]] *Step 3:* Run Camunda
====

To Run Camunda see the

- https://github.com/plungu/camunda-helm[HELM Chart] to install on Kubernetes

- or https://docs.camunda.org/manual/7.15/introduction/downloading-camunda/[Download a Distro or use SpringBoot]

- or https://docs.camunda.org/manual/7.15/installation/docker/[Run in Docker]

====

== [[optimize-setup]]Setup Optimize

==== [[optimize-version]] *Step 4:* Configure the version of Optimize
====
In this case the latest image is used. But we could swap different images and versions.

See the https://registry.camunda.cloud/harbor/projects/4/repositories[Camunda Harbor Repo] if you need a different version of Optimize.

*Pulling from the Enterprise Repo*

NOTE: you will need your enterprise credentials and an enterprise license for Optimize.

The version of Optimize can be changed in this section of the values.yaml

*Defaults Below*
[source,yaml]
----
image:
  repository: registry.camunda.cloud/optimize-ee/optimize
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: camunda-reg-cred
----

*Configuring the pullSecrets*

TIP: see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/[Configuring pull secrets kubernetes doc] for more info

Install the secret and name it camunda-reg-cred

----
kubectl create secret docker-registry camunda-reg-cred --docker-server=registry.camunda.cloud --docker-username=<<user>> --docker-password=<<password>> --docker-email=paul.lungu@camunda.com
----

Check your secret
----
kubectl get secret camunda-reg-cred --output=yaml

kubectl get secret camunda-reg-cred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
----

====

---

==== *Step 5:* [[optimize-connections]]Configure Optimize Connections
====
*Configure the connection to Camunda*

See <<running-camunda, Running Camunda>> to ensure you have a running Camunda instance.

See values.yaml to update configs. *Make sure to upadte the restUrl and webappsUrl with the correct config.*

*Defaults Below*
[source,yaml]
----
camunda:
  engine:
    name: "default"
    webappsEnabled: true
    restUrl: "http://10.1.0.40:8080/engine-rest"
    webappsUrl: "http://10.1.0.40:8080/camunda"
    importEnabled: true
    eventImportEnabled: true
    authentication:
      enabled: false
      user: ''
      password: ''
----

TIP: See the https://docs.camunda.org/optimize/develop/technical-guide/setup/configuration[possible configurations for Optimize]

*The environment-config ConfigMap defined in data-environment.yaml applies the configs to Optimize*
This will be mounted as a file in the Pod in the config directory as environment-config.yaml where Optimize can pick it up. If you wish to add additional configs you can use this config map and expose the variables in the values.yaml

*Defaults Below*
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "camunda-optimize.labels" . | nindent 4 }}
  name: environment-config
data:
  environment-config.yaml: |
    engines:
      'camunda-bpm':
        name: {{ .Values.camunda.engine.name }}
        rest: {{ .Values.camunda.engine.restUrl }}
        importEnabled: {{ .Values.camunda.engine.importEnabled }}
        eventImportEnabled: {{ .Values.camunda.engine.eventImportEnabled }}
        webapps:
          endpoint: {{ .Values.camunda.engine.webappsUrl }}
          enabled: {{ .Values.camunda.engine.webappsEnabled }}
        authentication:
          enabled: {{ .Values.camunda.engine.authentication.enabled }}
          user: {{ .Values.camunda.engine.authentication.user }}
          password: {{ .Values.camunda.engine.authentication.password }}
      es:
        connection.nodes[*]:
          host: {{ .Values.elasitc.external.host }}
          httpPort: {{ .Values.elasitc.external.port }}
----

*Configure Connection to Elastic Search*
See values.yaml to update configs

*Defaults Below*
[source,yaml]
----
elasitc:
  external:
    enabled: true
    host: "elasticsearch-master"
    port: "9200"
----

*Environment configs mounting definition in the deployment.yaml*
This is informational. Nothing to do unless you want to change the mount location or type.

[source,yaml]
----
          volumeMounts:
          - mountPath: /optimize/config/environment-config.yaml
            subPath: environment-config.yaml
            name: environment-config

      volumes:
      - name: environment-config
        configMap:
          name: environment-config
----
====

==== *Step 6:* [[optimize-license]]Configure the Optimize License
====
*Add your license to the data-license.yaml*

*Defaults Below*
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "camunda-optimize.labels" . | nindent 4 }}
  name: optimize-license
data:
  OptimizeLicense.txt:
    --------------- BEGIN CAMUNDA LICENSE KEY ---------------

    ---------------  END CAMUNDA LICENSE KEY  ---------------
----

*The license ConfigMap mounting definition in the deplyment.yaml*
This is informational. Nothing to do unless you want to change the mount location or type.
This will likly change to a secret in the near future.

[source,yaml]
----
          volumeMounts:
          - mountPath: /optimize/config/OptimizeLicense.txt
            subPath: OptimizeLicense.txt
            name: optimize-license

      volumes:
      - name: optimize-license
        configMap:
          name: optimize-license
----


//The `licenseSecertName:` allows us to use a secret resource for DB credentials.
//
//The `url:` uses the deployment name of the postgres resource. This is echoed in the notes after the install.

====
TIP: For more configuration options see https://github.com/camunda/docker-camunda-optimize/blob/next/README.md


==== [[optimize-run]] *Step 7:* Run the Chart
====
**Runing the Chart** the following command to install the chart and apply the configurations to the Kubernetes cluster
----
helm install optimize-demo ./charts/camunda-optimize/
----

**Change the Chart ** -- When you make changes run the following command to apply the changes to the cluster
----
helm upgrade optimize-demo ./charts/camunda-optimize/
----

**Remove the Chart **  -- To remove the installation
----
helm uninstall optimize-demo
----
====



== Whats Next
- [x] Configure Ingress and Scaling
- [x] Configuration for EE License (*In Progress*)
- [x] Configure common Optimize configs (Elastic, Engine)
- [ ] Configuration for Secrets Vault (HashiCorp, Spring Cloud Vault)
- [ ] Configuration for LDAP plugin
- [ ] Adding an Engine plugin
- [ ] Configuration for Logging
** [ ] Configuration for Log Drain
** [ ] Configuration for ARGO
** [ ] Configuration for TERRAFORM
- [ ] Configurations for SSO
** [ ] with Keycloak
- [ ] Configure auto-scaling
- [ ] Configure Cloud Deployments (GKE, AWS, Azure)



== Based on Camunda Helm
image:https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/camunda[link=https://artifacthub.io/packages/search?repo=camunda]

*More Info*

- https://docs.camunda.org/optimize/develop/technical-guide
- https://artifacthub.io/packages/helm/camunda/camunda-optimize
- https://github.com/elastic/helm-charts
- https://registry.camunda.cloud/harbor/projects/4/repositories
- https://kubernetes.github.io/ingress-nginx/deploy/#docker-for-mac
- https://helm.sh/docs/intro/quickstart/
- https://hub.docker.com/r/camunda/camunda-optimize
- https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
- https://github.com/camunda/camunda-helm
- https://github.com/camunda/docker-camunda-optimize



== Project state

This project is in **alpha** phase.
